// De bronteksten van het spel (vraag 147): elke zin die de speler kan zien, in het Engels, en in welke bestanden
// hij staat. Gemaakt door npm run teksten (gereedschap/teksten.cjs) uit de aanroepen van T.t in js/; niet met de
// hand bewerken. De vertaaltool (gereedschap/vertalen.html) werkt met deze lijst.
Spel.TAAL_BRON = [
  {"t":"Autosave","waar":["js/menu.js"]},
  {"t":"Slot {plek}","waar":["js/menu.js"]},
  {"t":"today {tijd}","waar":["js/menu.js"]},
  {"t":"yesterday {tijd}","waar":["js/menu.js"]},
  {"t":"{datum}, {uur} · {n|# person|# people} · {wanneer}","waar":["js/menu.js"]},
  {"t":"Continue","waar":["js/menu.js"]},
  {"t":"New game","waar":["js/menu.js"]},
  {"t":"Load","waar":["js/menu.js"]},
  {"t":"Game rules","waar":["js/menu.js"]},
  {"t":"Language","waar":["js/menu.js"]},
  {"t":"Resume","waar":["js/menu.js"]},
  {"t":"Save","waar":["js/menu.js"]},
  {"t":"Nothing has been saved yet.","waar":["js/menu.js"]},
  {"t":"Photo mode","waar":["js/menu.js"]},
  {"t":"Everything off the screen, for a picture. H in the game.","waar":["js/menu.js"]},
  {"t":"To the title screen","waar":["js/menu.js"]},
  {"t":"empty","waar":["js/menu.js"]},
  {"t":"your own translation","waar":["js/menu.js"]},
  {"t":"Back","waar":["js/menu.js"]},
  {"t":"What is your village called?","waar":["js/menu.js"]},
  {"t":"The land","waar":["js/menu.js"]},
  {"t":"Another land, from a new number","waar":["js/menu.js"]},
  {"t":"Other land","waar":["js/menu.js"]},
  {"t":"Begin","waar":["js/menu.js"]},
  {"t":"Save to","waar":["js/menu.js"]},
  {"t":"Load from","waar":["js/menu.js"]},
  {"t":"Menu","waar":["js/menu.js"]},
  {"t":"Close (Esc)","waar":["js/menu.js"]},
  {"t":"{plek} loaded: {datum}.","waar":["js/menu.js"]},
  {"t":"Saved to slot {plek}.","waar":["js/menu.js"]},
  {"t":"Start a new game? The autosave will be overwritten. Your own slots stay.","waar":["js/menu.js"]},
  {"t":"Back to the title screen? Anything since your last save will be lost.","waar":["js/menu.js"]},
  {"t":"Overwrite {plek}? It now holds {wat}.","waar":["js/menu.js"]},
  {"t":"a game that no longer fits","waar":["js/menu.js"]},
  {"t":"Overwrite","waar":["js/menu.js"]},
  {"t":"Load this game? Anything since your last save will be lost.","waar":["js/menu.js"]},
  {"t":"The game could not autosave: {reden}","waar":["js/menu.js"]},
  {"t":"Photo mode · drag or arrows to look · wheel to zoom · [Enter] saves a picture · [H] or [Esc] to return","waar":["js/main.js"]},
  {"t":"Picture saved: {naam}","waar":["js/main.js"]},
];
