// Nederlands (nl): de vertaling van de spelteksten (vraag 147). Per Engelse zin uit het spel wat hij in
// deze taal is. Gemaakt en bijgehouden met de vertaaltool (gereedschap/vertalen.html); zie js/taal.js.
Spel.taal({
  "code": "nl",
  "naam": "Nederlands",
  "locale": "nl-NL",
  "zinnen": {
    "Autosave": "Vanzelf bewaard",
    "Slot {plek}": "Plek {plek}",
    "today {tijd}": "vandaag {tijd}",
    "yesterday {tijd}": "gisteren {tijd}",
    "{datum}, {uur} · {n|# person|# people} · {wanneer}": "{datum}, {uur} · {n|# mens|# mensen} · {wanneer}",
    "Continue": "Verder",
    "New game": "Nieuw spel",
    "Load": "Laden",
    "Game rules": "Spelregels",
    "Language": "Taal",
    "Resume": "Verder spelen",
    "Save": "Opslaan",
    "Nothing has been saved yet.": "Er is nog niets bewaard.",
    "Photo mode": "Fotomodus",
    "Everything off the screen, for a picture. H in the game.": "Alles van het beeld, voor een plaatje. H in het spel.",
    "To the title screen": "Naar het titelscherm",
    "empty": "leeg",
    "your own translation": "je eigen vertaling",
    "Back": "Terug",
    "What is your village called?": "Hoe heet je dorp?",
    "The land": "Het land",
    "Another land, from a new number": "Een ander land, uit een nieuw nummer",
    "Other land": "Ander land",
    "Begin": "Begin",
    "Save to": "Opslaan op",
    "Load from": "Laden van",
    "Menu": "Menu",
    "Close (Esc)": "Sluiten (Esc)",
    "{plek} loaded: {datum}.": "{plek} geladen: {datum}.",
    "Saved to slot {plek}.": "Opgeslagen op plek {plek}.",
    "Start a new game? The autosave will be overwritten. Your own slots stay.": "Een nieuw spel beginnen? Wat er vanzelf bewaard is, wordt dan overschreven. Je eigen plekken blijven.",
    "Back to the title screen? Anything since your last save will be lost.": "Naar het titelscherm? Wat je sinds het laatste opslaan deed, ben je kwijt.",
    "Overwrite {plek}? It now holds {wat}.": "{plek} overschrijven? Daar staat nu {wat}.",
    "a game that no longer fits": "een spel dat niet meer past",
    "Overwrite": "Overschrijven",
    "Load this game? Anything since your last save will be lost.": "Dit spel laden? Wat je sinds het laatste opslaan deed, ben je kwijt.",
    "The game could not autosave: {reden}": "Het spel kon niet vanzelf opslaan: {reden}",
    "Photo mode · drag or arrows to look · wheel to zoom · [Enter] saves a picture · [H] or [Esc] to return": "Fotomodus · slepen of pijltjes om te kijken · wiel: verder of dichterbij · [Enter] bewaart een plaatje · [H] of [Esc]: terug",
    "Picture saved: {naam}": "Plaatje bewaard: {naam}"
  }
});
